import type { Metadata } from "next";
import "./globals.css";
import vazirMatn from "@/utils/fonts";
import Layout from "@/components/layout/Layout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vazirMatn.className}  antialiased  dark:text-white dark:bg-gray-900 bg-stone-100`}
      >
        <Layout>
        {children}
        </Layout>
      </body>
    </html>
  );
}
